package com.sushi.sushihouse.utility;

public enum StatusOrder {
	USER_MADE_AN_ORDER,
	
	CONFIRMED_MANAGER,
	CONFIRMED_WAITER,
	
	COOK_ORDER_IS_READY_DELIVERY,
	COOK_ORDER_IS_READY_WAITER,
	COOK_PROBLEM,
	COOK_NOT_PROBLEM,
	
	DELIVERED_ORDER,
	DELIVERY_PROBLEM,
	DELIVERY_NOT_PROBLEM
}
